### ISSUE TITLE
Hipchat API backend is broken

### ISSUE THREAD

**Issue by gbin** [gbin/err#220]
If you try to put a hipchat API token it breaks.

Apparently hipchat published a V2 of their API, it might be the good opportunity to port err to it.

```
DEBUG:root:Message intercepted for Hipchat API
ERROR:root:Command failedTraceback (most recent call last):  
File "/usr/local/google/home/gbin/projects/err/errbot/backends/base.py", line 437, in _execute_and_send    if reply: send_reply(process_reply(reply))  
File "/usr/local/google/home/gbin/projects/err/errbot/backends/base.py", line 428, in send_reply    self.send_simple_reply(mess, part, cmd in DIVERT_TO_PRIVATE) 
 File "/usr/local/google/home/gbin/projects/err/errbot/backends/base.py", line 250, in send_simple_reply    self.send_message(self.build_reply(mess, text, private))  File "/usr/local/google/home/gbin/projects/err/errbot/errBot.py", line 124, in send_message    super(ErrBot, self).send_message(mess)
File "/usr/local/google/home/gbin/projects/err/errbot/backends/base.py", line 246, in send_message    self.connect().send_message(mess)
File "/usr/local/google/home/gbin/projects/err/errbot/backends/hipchat.py", line 47, in send_message    self.send_api_message(room_jid.getNode().split('_')[1], CHATROOM_FN, content)
File "/usr/local/google/home/gbin/projects/err/errbot/backends/hipchat.py", line 39, in send_api_message    return json.load(urlopen(req))
File "/usr/lib/python3.2/urllib/request.py", line 138, in urlopen    return opener.open(url, data, timeout)

File "/usr/lib/python3.2/urllib/request.py", line 367, in open    req = meth(req)
File "/usr/lib/python3.2/urllib/request.py", line 1065, in do_request_    

raise TypeError("POST data should be bytes"

TypeError: POST data should be bytes or an iterable of bytes. It cannot be str.
```

**Comment by zoni** [comment]
This was fixed by the new HipChat back-end that's in 2.0
