### ISSUE TITLE
XEP-0249 plugin fails to load with Yapsy >= 1.11

### ISSUE THREAD

**Issue by amorphic** [gbin/err#338]
Under err 2.2.0b0, invocation of the XEP-0249 plugin on startup fails with the following:

```
08:36:43 DEBUG    sleekxmpp.plugins.base    Loaded Plugin: XEP-0249: Direct MUC Invitations
Traceback (most recent call last):
  File "/opt/optiver/virtualenvs/bots/obot/bin/err.py", line 245, in <module>
    main(bot_class, logger, config)
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/errbot/main.py", line 46, in main
    errors = holder.bot.update_dynamic_plugins()
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/errbot/errBot.py", line 177, in update_dynamic_plugins
    self.bot_config.BOT_EXTRA_PLUGIN_DIR)
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/errbot/plugin_manager.py", line 192, in update_plugin_places
    simplePluginManager.locatePlugins()
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/yapsy/PluginManager.py", line 442, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 432, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 386, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/opt/optiver/virtualenvs/bots/obot/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 266, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.
```

This seems to have began with [Yapsy 1.11.23 released on 2015-04-05](https://pypi.python.org/pypi/Yapsy/1.11.023). Downgrading Yapsy to the previous release (1.10.423) fixes the problem.

So I see two issues here:

1. Err is incompatible with breaking [changes made to Yapsy in the 1.11.23 release](https://github.com/tibonihoo/yapsy/compare/release_Yapsy-1.11.023...master).
2. Err does not explicitly limit dependency versions to "known good" versions in `setup.py`.

**Comment by gbin** [comment]
Indeed, reproduced on travis ... It looks like it is a python 2.7 problem only.

**Comment by tobika** [comment]
thanks for the info, I also just downgraded Yapsy and it worked
python 2.7 here

**Comment by gbin** [comment]
I have restricted the downgrade for python2.7 only as it works perfectly under py3 and I don't feel like digging this bug if it doesn't become a problem for py2 folks. If it is please feel free to reopen.

**Comment by garretholland** [comment]
This has popped up for me on 3.6

 'text': 'Some plugins failed to start during bot startup:\n'
         ' File "c:\\program '
         'files\\python36\\lib\\site-packages\\yapsy\\PluginManager.py", line '
         '488, in loadPlugins\n'
         '    candidate_module = '
         'imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py
",("py","r",imp.PY_SOURCE))\n'
         '  File "c:\\program files\\python36\\lib\\imp.py", line 234, in '
         'load_module\n'
         '    return load_source(name, filename, file)\n'
         '  File "c:\\program files\\python36\\lib\\imp.py", line 172, in '
         'load_source\n'
         '    module = _load(spec)\n'
         '  File "&lt;frozen importlib._bootstrap&gt;", line 675, in _load\n'
         '  File "&lt;frozen importlib._bootstrap&gt;", line 655, in '
         '_load_unlocked\n'
         '  File "&lt;frozen importlib._bootstrap_external&gt;", line 674, in '
         'exec_module\n'
         '  File "&lt;frozen importlib._bootstrap_external&gt;", line 781, in '
         'get_code\n'
         '  File "&lt;frozen importlib._bootstrap_external&gt;", line 741, in '
         'source_to_code\n'
         '  File "&lt;frozen importlib._bootstrap&gt;", line 205, in '
         '_call_with_frames_removed',
 'ts': '1489281519.885953',
 'type': 'message',
 'user': 'U4E9EDX29'}←[0m
17:18:39 ←[36mDEBUG   ←[0m ←[34merrbot.backends.slack    ←[0m ←[37mEscaped IDs e
vent text: Some plugins failed to start during bot startup:
 File "c:\program files\python36\lib\site-packages\yapsy\PluginManager.py", line
 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_
filepath+".py",("py","r",imp.PY_SOURCE))
  File "c:\program files\python36\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "c:\program files\python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "&lt;frozen importlib._bootstrap&gt;", line 675, in _load
  File "&lt;frozen importlib._bootstrap&gt;", line 655, in _load_unlocked
  File "&lt;frozen importlib._bootstrap_external&gt;", line 674, in exec_module
  File "&lt;frozen importlib._bootstrap_external&gt;", line 781, in get_code
  File "&lt;frozen importlib._bootstrap_external&gt;", line 741, in source_to_co
de
  File "&lt;frozen importlib._bootstrap&gt;", line 205, in _call_with_frames_rem
oved←[0m
17:18:39 ←[36mDEBUG   ←[0m ←[34merrbot.core              ←[0m ←[37mIgnoring mess
age from self←[0m
17:18:59 ←[36mDEBUG   ←[0m ←[34merrbot.backends.slack    ←[0m ←[37mProcessing sl
ack event: {'type': 'presence_change', 'presence': 'away', 'user': 'U032B1N20'}←
[0m

**Comment by cuckoo-linux** [comment]
how to downgrade yapsy.please tell

**Comment by definitelynotkorean** [comment]
@cuckoo-linux Hey I just random saw your comment and maybe I could answer your question, even though I am new to Python :D (Also hard-working on it)
In the first topic. There's a stable version they mentioned (1.10.423)
You need to [uninstall the previous version you installed](https://stackoverflow.com/questions/1231688/how-do-i-remove-packages-installed-with-pythons-easy-install) first
Then [download](https://sourceforge.net/projects/yapsy/files/Yapsy-1.10.423/) and install the specific version you'd like to go
I'm testing on the old version of yapsy to see whether it works or not. 

Hope my answer helps you. Also, any correction is welcome :P
