### ISSUE TITLE
Install on Ubuntu (ok, Mint) results in error

### ISSUE THREAD

**Issue by kenden** [gbin/err#383]
Error when installing via "pip install err"
"No package 'libffi' found"

```
$ uname -a
Linux machone 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux


$ python --version
Python 2.7.6

$ dpkg --list python-dev
\Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  python-dev               2.7.5-5ubuntu3    amd64             header files and a static library for Python (default

$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip, wheel...done.

$ pip install err
Collecting err
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from err)
Requirement already satisfied (use --upgrade to upgrade): daemonize in ./venv/lib/python2.7/site-packages (from err)
Collecting pyOpenSSL (from err)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in ./venv/lib/python2.7/site-packages (from err)
Requirement already satisfied (use --upgrade to upgrade): bottle in ./venv/lib/python2.7/site-packages (from err)
Collecting config (from err)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in ./venv/lib/python2.7/site-packages (from err)
Requirement already satisfied (use --upgrade to upgrade): webtest in ./venv/lib/python2.7/site-packages (from err)
Collecting yapsy (from err)
Collecting colorlog (from err)
  Using cached colorlog-2.6.0-py2.py3-none-any.whl
Collecting dnspython (from err)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in ./venv/lib/python2.7/site-packages (from pyOpenSSL->err)
Collecting cryptography>=0.7 (from pyOpenSSL->err)
  Using cached cryptography-0.9.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): markupsafe in ./venv/lib/python2.7/site-packages (from jinja2->err)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in ./venv/lib/python2.7/site-packages (from webtest->err)
Requirement already satisfied (use --upgrade to upgrade): WebOb>=1.2 in ./venv/lib/python2.7/site-packages (from webtest->err)
Requirement already satisfied (use --upgrade to upgrade): waitress>=0.8.5 in ./venv/lib/python2.7/site-packages (from webtest->err)
Requirement already satisfied (use --upgrade to upgrade): idna in ./venv/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->err)
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in ./venv/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->err)
Requirement already satisfied (use --upgrade to upgrade): enum34 in ./venv/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->err)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in ./venv/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->err)
Collecting cffi>=0.8 (from cryptography>=0.7->pyOpenSSL->err)
  Using cached cffi-1.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./venv/lib/python2.7/site-packages (from cffi>=0.8->cryptography>=0.7->pyOpenSSL->err)
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography
  Complete output from command /home/qna/dev/python/test_err/venv/bin/python -c "import setuptools;__file__='/tmp/pip-build-vt2Vr9/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp7q14YRpip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vt2Vr9/cryptography/setup.py", line 342, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
      return self.obtain(req, installer)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
      return installer(requirement)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/home/qna/dev/python/test_err/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py bdist_wheel for cffi
  Complete output from command /home/qna/dev/python/test_err/venv/bin/python -c "import setuptools;__file__='/tmp/pip-build-vt2Vr9/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpRdN5xhpip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/c
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cffi
Failed to build cryptography cffi
Installing collected packages: cffi, cryptography, pyOpenSSL, config, yapsy, colorlog, dnspython, err
  Running setup.py install for cffi
    Complete output from command /home/qna/dev/python/test_err/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-vt2Vr9/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8bUIFh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/qna/dev/python/test_err/venv/include/site/python2.7/cffi:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    running build_ext
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/qna/dev/python/test_err/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-vt2Vr9/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8bUIFh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/qna/dev/python/test_err/venv/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-vt2Vr9/cffi
```

**Comment by kenden** [comment]
I found the solution:
```
sudo apt-get install libffi-dev
```

From:
http://askubuntu.com/questions/499714/error-installing-scrapy-in-virtualenv-using-pip

Suggestion: add this in the doc?
