### ISSUE TITLE
Slack backend doesn't handle newly registered users joining

### ISSUE THREAD

**Issue by LuckyHyena** [gbin/err#384]
Latest master.zip as of 2015-6-29
Need to update the local user cache with the new user's information

https://api.slack.com/events/team_join
https://api.slack.com/types/user

```
14:12:44 DEBUG    errbot.backends.slack     No event handler available for team_join, ignoring this event
14:12:45 DEBUG    errbot.backends.slack     Processing slack event: {'user': 'U000001', 'ts': '1435605167.001363', 'type': 'message', 'subtype': 'channel_join', 'text': '<@U000001|username> has joined the channel', 'channel': 'C000001'}
14:12:45 DEBUG    errbot.backends.slack     Handling message from a public channel
14:12:45 ERROR    errbot.backends.slack     message event handler raised an exception
Traceback (most recent call last):
  File "/home/whiskeyriver/Code/err/errbot/backends/slack.py", line 155, in serve_once
    event_handler(message)
  File "/home/whiskeyriver/Code/err/errbot/backends/slack.py", line 213, in _message_event_handler
    resource=self.userid_to_username(event['user'])
  File "/home/whiskeyriver/Code/err/errbot/backends/slack.py", line 227, in userid_to_username
    raise UserDoesNotExistError("Cannot find user with ID %s" % id)
errbot.backends.base.UserDoesNotExistError: Cannot find user with ID U000001
14:12:49 DEBUG    errbot.backends.slack     Processing slack event: {'user': 'U000001', 'type': 'presence_change', 'presence': 'active'}
```

**Comment by gbin** [comment]
I tried to fix it here : #394
It you have some time, can you check if it is correct ?
Thx

**Comment by LuckyHyena** [comment]
im running on that branch today, i don't know if/when we'll get new team members though

**Comment by gbin** [comment]
I merged the branch, this should fix it, we will revisit that if upstream fixed it correctly
