### ISSUE TITLE
Could not find the backend 'Slack'; ImportError: cannot import name 'build_message'

### ISSUE THREAD

**Issue by LuckyHyena** [gbin/err#407]
Issue after installing the latest master.zip

```
(ve-err)whiskeyriver@whiskeyriver-VirtualBox:~/Code/errbot/tools/errbot$ err.py
12:28:17 INFO     __main__                  Config check passed...
12:28:17 INFO     __main__                  Selected backend 'Slack'.
12:28:17 INFO     __main__                  Checking for '/home/whiskeyriver/Code/errbot/tools/errbot/var/data'...
12:28:17 INFO     errbot.backend_manager    Backends search paths ['/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends']
12:28:17 INFO     errbot.backend_manager    Found those backends available:
12:28:17 INFO     errbot.backend_manager          Campfire  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/campfire.py)
12:28:17 INFO     errbot.backend_manager           Graphic  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/graphic.py)
12:28:17 INFO     errbot.backend_manager              Null  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/null.py)
12:28:17 INFO     errbot.backend_manager               IRC  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/irc.py)
12:28:17 INFO     errbot.backend_manager              Text  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/text.py)
12:28:17 INFO     errbot.backend_manager              Test  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/test.py)
12:28:17 INFO     errbot.backend_manager               Tox  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/tox.py)
12:28:17 INFO     errbot.backend_manager           Hipchat  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/hipchat.py)
12:28:17 INFO     errbot.backend_manager              XMPP  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/xmpp.py)
12:28:17 INFO     errbot.backend_manager             Slack  (/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/slack.py)
12:28:17 INFO     errbot.main               Found Backend plugin: 'Slack'
                        Description: This is the slack backend for Err.
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/campfire.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/graphic.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/null.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/irc.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/text.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/test.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/tox.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/hipchat.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 WARNING  yapsy                     Plugin candidate '/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/xmpp.plug'  rejected by strategy 'SpecificBackendLocator'
12:28:17 ERROR    yapsy                     Unable to import plugin: /home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/slack
Traceback (most recent call last):
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backends/slack.py", line 8, in <module>
    from errbot.backends.base import (
ImportError: cannot import name 'build_message'
12:28:17 ERROR    errbot.main               Unable to configure the backend, please check if your config.py is correct.
Traceback (most recent call last):
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/main.py", line 53, in setup_bot
    bot = bpm.get_backend_by_name(backend_name)
  File "/home/whiskeyriver/Code/errbot/tools/errbot/var/ve-err/lib/python3.4/site-packages/errbot/backend_manager.py", line 78, in get_backend_by_name
    raise Exception("Could not find the backend '%s'." % name)
Exception: Could not find the backend 'Slack'.
(ve-err)whiskeyriver@whiskeyriver-VirtualBox:~/Code/errbot/tools/errbot$
```

**Comment by gbin** [comment]
just pushed the fixed (it was also reported on gitter.im), thx for reporting it !

**Comment by gbin** [comment]
https://github.com/gbin/err/commit/8e6a8247c707cc23da7dfe709e493d789abc964b
