### ISSUE TITLE
executing !repos not working

### ISSUE THREAD

**Issue by sijis** [gbin/err#435]
Executing !repos in Slack backend is causing a disconnect and reconnect of the bot. No output is ever returned from bot

```
14:06:02 DEBUG    errbot.backends.slack     Processing slack event: {'type': 'message', 'channel': 'D04V0HUP5', 'team': 'T03FB98Q1', 'ts': '1438715161.000192', 'user': 'U03FDUZAQ', 'text': '.repos'}
14:06:02 DEBUG    errbot.backends.slack     Handling message from a user
14:06:02 DEBUG    errbot.errBot             *** frm = @saviles
14:06:02 DEBUG    errbot.errBot             *** username = U03FDUZAQ
14:06:02 DEBUG    errbot.errBot             *** type = chat
14:06:02 DEBUG    errbot.errBot             *** text = .repos
14:06:02 INFO     errbot.errBot             Processing command 'repos' with parameters '' from @saviles
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on ChatRoom
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on Health
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on Backup
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on VersionChecker
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on Plugins
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on Utils
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on StalkerBot
14:06:02 ERROR    errbot.errBot             Crash in a callback_message handler
Traceback (most recent call last):
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/errBot.py", line 543, in callback_message
    plugin.callback_message(mess)
  File "/home/saviles/data/apps/errbot/plugins/err-stalkerbot/stalkerBot.py", line 18, in callback_message
    username = str(mess.nick)
AttributeError: 'Message' object has no attribute 'nick'
14:06:02 DEBUG    errbot.backends.slack     Sending chat message to saviles (D04V0HUP5)
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on Help
14:06:02 DEBUG    errbot.errBot             Trigger callback_message on HostedGraphite
14:06:03 ERROR    errbot.backends.slack     Error reading from RTM stream:
Traceback (most recent call last):
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/backends/slack.py", line 215, in serve_once
    for message in self.sc.rtm_read():
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/slackclient/_client.py", line 27, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/slackclient/_server.py", line 109, in websocket_safe_read
    data += "{}\n".format(self.websocket.recv())
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_core.py", line 476, in _recv
    return recv(self.sock, bufsize)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
14:06:03 DEBUG    errbot.backends.slack     Triggering disconnect callback
14:06:03 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
14:06:03 DEBUG    errbot.storage            Closed shelf of ChatRoom
14:06:03 DEBUG    errbot.storage            Closed shelf of Health
14:06:03 DEBUG    errbot.storage            Closed shelf of Backup
14:06:03 DEBUG    errbot.botplugin          You still have active pollers at deactivation stage, I cleaned them up for you.
14:06:03 DEBUG    errbot.storage            Closed shelf of VersionChecker
14:06:03 DEBUG    errbot.storage            Closed shelf of Plugins
14:06:03 DEBUG    errbot.storage            Closed shelf of Utils
14:06:03 DEBUG    errbot.storage            Closed shelf of StalkerBot
14:06:03 DEBUG    errbot.storage            Closed shelf of Help
14:06:03 DEBUG    errbot.storage            Closed shelf of HostedGraphite
14:06:03 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far)
14:06:04 INFO     errbot.backends.slack     Verifying authentication token
14:06:04 DEBUG    errbot.backends.slack     Token accepted
14:06:04 INFO     errbot.backends.slack     Connecting to Slack real-time-messaging API
14:06:06 INFO     errbot.backends.slack     Connected
```

**Comment by gbin** [comment]
This was a message size limit issue, fixed by 4db20136e7fe7680361fe58fba2009ea70f11007
