### ISSUE TITLE
slack: Unparseable slack identifier

### ISSUE THREAD

**Issue by sijis** [gbin/err#436]
Upon loading the bot, i'm seeing the following on the slack backend

```
4:18:20 DEBUG    errbot.backends.slack     building an identifier from saviles
14:18:20 ERROR    errbot.backends.slack     hello event handler raised an exception
Traceback (most recent call last):
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/backends/slack.py", line 227, in serve_once
    event_handler(message)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/backends/slack.py", line 244, in _hello_event_handler
    self.connect_callback()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/errBot.py", line 596, in connect_callback
    loading_errors = self.activate_non_started_plugins()
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/plugin_manager.py", line 365, in activate_non_started_plugins
    self.warn_admins(errors)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/errBot.py", line 474, in warn_admins
    self.send(admin, warning)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/errBot.py", line 509, in send
    user = self.build_identifier(s)
  File "/home/saviles/virtualenvs/errbot-py3-slim/lib/python3.4/site-packages/errbot/backends/slack.py", line 423, in build_identifier
    "should be #channelname/username or @username : '%s'" % txtrep)
Exception: Unparseable slack identifier, should be #channelname/username or @username : 'saviles'
```

It doesn't seem to be causing a problem in functionality.

Sijis

**Comment by gbin** [comment]
It means errbot tried to send a message directly to BOT_ADMINS but it is not in the format the service is expecting it.

As a fix, should we add the @ by default if it is not there or make the users add an @ to the config file ?

**Comment by sijis** [comment]
Adding the @sijis to the config, suppressed the issue.

Its probably a good idea to prefix the username with an @ character. We could also put examples in the config.py of the format expected for the backend. Maybe this is more of a documentation thing.

Sijis
