### ISSUE TITLE
Sending a direct message to the bot using XMPP fails

### ISSUE THREAD

**Issue by lairsdragon** [gbin/err#441]
Using the XMPP backend, sending a direct message to the errbot fails with following error message: 

```log
21:59:07 ERROR    sleekxmpp.xmlstream.xmlst Error processing event handler: <bound method XMPPBackend.incoming_message of <yapsy_loaded_plugin_XMPP_0.XMPPBackend object at 0x7f280057f048>>
Traceback (most recent call last):
  File "/home/vagrant/errbot/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 477, in incoming_message
    msg.to = self.build_identifier(xmppmsg['to'].full)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 590, in build_identifier
    domain, resource = domain.split('/')
ValueError: too many values to unpack (expected 2)
21:59:07 ERROR    sleekxmpp.stanza.rootstan Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/home/vagrant/errbot/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 477, in incoming_message
    msg.to = self.build_identifier(xmppmsg['to'].full)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 590, in build_identifier
    domain, resource = domain.split('/')
ValueError: too many values to unpack (expected 2)
21:59:07 ERROR    sleekxmpp.basexmpp        too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/vagrant/errbot/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 477, in incoming_message
    msg.to = self.build_identifier(xmppmsg['to'].full)
  File "/home/vagrant/errbot/lib/python3.4/site-packages/errbot/backends/xmpp.py", line 590, in build_identifier
    domain, resource = domain.split('/')
ValueError: too many values to unpack (expected 2)

```

**Comment by lairsdragon** [comment]
i've found that one identity on my xmpp server Looks like this: `user@xmpp.server.tld/huhu/whatever` and that causes the error. 

I changed the domain.split("/") to domain.split("/",1) and that fixed this for me.
