### ISSUE TITLE
!gtalk room_create is borked

### ISSUE THREAD

**Issue by sijis** [gbin/err#444]
The botcmd in Chatroom core plugins is borked.

```
2015-08-12 14:33:48,758 ERROR An error happened while processing a message (".gtalk room_create"): Traceback (most recent call last):
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/errBot.py", line 358, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 256, in gtalk_room_create
    self.join_room(room_name)
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/botplugin.py", line 363, in join_room
    return self._bot.join_room(room, username, password)
TypeError: __call__() takes 2 positional arguments but 4 were given
"
Traceback (most recent call last):
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/errBot.py", line 358, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 256, in gtalk_room_create
    self.join_room(room_name)
  File "/opt/virtualenv/errbot3/lib/python3.4/site-packages/errbot/botplugin.py", line 363, in join_room
    return self._bot.join_room(room, username, password)
TypeError: __call__() takes 2 positional arguments but 4 were given
```

**Comment by gbin** [comment]
I just removed the XMPP/gtalk support, this has been deprecated since february 2015 so there is no point supporting this in 3.0. User can still stay on 2.2.x until they find an alternative solution.
