### ISSUE TITLE
IRC back-end fails to load

### ISSUE THREAD

**Issue by znorris** [gbin/err#453]
Issue: Unable to load IRC back-end. 
Cause: Due to missing elements in CharacterTable. Specifically "inline_code" and "end_inline_code".
Err Version: 3.0.0

Copy of error:
```
21:24:39 DEBUG errbot.backend_manager Load the one remaining...
21:24:39 ERROR yapsy Unable to import plugin: /usr/local/lib/python3.4/dist-packages/errbot/backends/irc
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginManager.py", line 488, in loadPlugins
candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
File "/usr/lib/python3.4/imp.py", line 235, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.4/imp.py", line 171, in load_source
module = methods.load()
File "<frozen importlib._bootstrap>", line 1220, in load
File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
File "<frozen importlib._bootstrap>", line 1129, in _exec
File "<frozen importlib._bootstrap>", line 1448, in exec_module
File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
File "/usr/local/lib/python3.4/dist-packages/errbot/backends/irc.py", line 47, in <module>
end_fixed_width='')
TypeError: __new__() missing 2 required positional arguments: 'inline_code' and 'end_inline_code'
21:24:39 DEBUG errbot.backend_manager Find it back...
21:24:39 ERROR errbot.main Unable to configure the backend, please check if your config.py is correct.
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/errbot/main.py", line 53, in setup_bot
bot = bpm.get_backend_by_name(backend_name)
File "/usr/local/lib/python3.4/dist-packages/errbot/backend_manager.py", line 85, in get_backend_by_name
raise Exception("Could not find the backend '%s'." % name)
Exception: Could not find the backend 'IRC'.
```

**Comment by gbin** [comment]
Thx for the fix
