### ISSUE TITLE
3to2 doesn't convert urllib correctly (was: Domain contains illegal characters)

### ISSUE THREAD

**Issue by ramonamis** [gbin/err#460]
Hello, 

I am already succesfully running an instance of err (2.2.1)+ hipchat, and i am trying to set up a second one on another machine, with mostly the same code base except the bot has another identity.
For some weird reason, with the same verison of the package and the same dependencies installed (I am using salt for automation) the instance i am trying to set up is using different code (yes, i am using 3to2 but for some reason it does not behave as expected. 

First issue i have is with urllib:
```
Traceback (most recent call last):
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/errbot/builtins/vcheck.py", line 4, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```
I went around and fixed this manually in some places and now i get this wonderful error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1679, in _event_runner
    orig.exception(e)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/stanza/rootstanza.py", line 75, in exception
    self.reply()
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/stanza/message.py", line 139, in reply
    StanzaBase.reply(self, clear)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1550, in reply
    self['to'] = self['from']
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 695, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1501, in get_from
    return JID(self._get_attr('from'))
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
InvalidJID: Domain contains illegal characters
```

I am wondering which domain exactly has illegal characters, i compared the 2 config files (the one of the instance which is working and one of the instance which is not) and i do not really see any difference. 

Any help is highly appreciated.

**Comment by gbin** [comment]
Can you add a debug log like log.info("jid: %s" % jid) in this sleekxmpp.py __init__ ? The weird thing is that it doesn't touch Errbot code for the entire stacktrace.

Can you check `locale -a' from the 2 instances and compare ?

**Comment by ramonamis** [comment]
locale -a: 

*Working:
```
locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

*Not working:
```C
C.UTF-8
de_AT.utf8
de_BE.utf8
de_CH.utf8
de_DE.utf8
de_LI.utf8
de_LU.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

I added that debug line in the jid.py file, and it fails because my rooms have "_" inside their names. Actually, that is the standard room naming for hipchat i think;

```
#: These characters are not allowed to appear in a JID.
ILLEGAL_CHARS = '\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r' + \
                '\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19' + \
                '\x1a\x1b\x1c\x1d\x1e\x1f' + \
                ' !"#$%&\'()*+,./:;<=>?@[\\]^_`{|}~\x7f'
```

And ^^ are the illegal characters; i did a pip freeze and checked sleekxmpp version, i have same version on both servers: 1.3.1

Thanks a lot for your fast response

**Comment by ramonamis** [comment]
i removed "_" from illegal characters, now i get:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1679, in _event_runner
    orig.exception(e)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/stanza/rootstanza.py", line 75, in exception
    self.reply()
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/stanza/message.py", line 139, in reply
    StanzaBase.reply(self, clear)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1550, in reply
    self['to'] = self['from']
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 695, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/stanzabase.py", line 1501, in get_from
    return JID(self._get_attr('from'))
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 465, in __init__
    parsed_jid = _parse_jid(jid)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 153, in _parse_jid
    domain = _validate_domain(domain)
  File "/home/hildasan/.virtualenvs/hilda-san-env/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 227, in _validate_domain
    raise InvalidJID('Could not encode domain as ASCII')
InvalidJID: Could not encode domain as ASCII
```

**Comment by gbin** [comment]
but it complains about the domain right ?
usually it is:
room@domain.tld/user the format

**Comment by ramonamis** [comment]
I added here: https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/jid.py#L192
```
    import logging
    log = logging.getLogger(__name__)
    log.info('DOMAIN: %s' % domain)
```
And i get:
```
11:05:11 INFO     sleekxmpp.jid             DOMAIN: chat.hipchat.com
11:05:11 INFO     sleekxmpp.jid             DOMAIN: chat.hipchat.com
11:05:11 INFO     sleekxmpp.jid             DOMAIN: chat.hipchat.com
11:05:11 INFO     sleekxmpp.jid             DOMAIN: 6
11:05:11 INFO     sleekxmpp.jid             DOMAIN: 1
11:05:11 INFO     sleekxmpp.jid             DOMAIN: 3
11:05:11 INFO     sleekxmpp.jid             DOMAIN: 8
11:05:11 INFO     sleekxmpp.jid             DOMAIN: _
```

And then here: https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/jid.py#L144
```
    import logging
    log = logging.getLogger(__name__)
    log.info('DATA: %s' % data)
```
and i get:
```
11:07:57 INFO     sleekxmpp.jid             DATA: 61338_477162@chat.hipchat.com
11:07:57 INFO     sleekxmpp.jid             DATA: 61338_477163@chat.hipchat.com
11:07:57 INFO     sleekxmpp.jid             DATA: 61338_1505265@chat.hipchat.com
11:07:57 INFO     sleekxmpp.jid             DATA: 61338_2103291@chat.hipchat.com
11:07:57 INFO     sleekxmpp.jid             DATA: 61338_2103294@chat.hipchat.com
11:07:57 INFO     sleekxmpp.jid             DATA: 6
11:07:57 INFO     sleekxmpp.jid             DATA: 1
11:07:57 INFO     sleekxmpp.jid             DATA: 3
11:07:57 INFO     sleekxmpp.jid             DATA: 8
11:07:57 INFO     sleekxmpp.jid             DATA: _
```

This looks like sleekxmpp issue, but still, i have the same version of the library on the other working instance and it works. @gbin what do you think?

**Comment by ramonamis** [comment]
@gbin i have found the issue. in my config file the ',' was missing, here:

BOT_ADMINS = (u'xxxx_xxxxxxx@chat.hipchat.com',)
 I am wondering, why do you need a , there? maybe the error messages can be improved somehow?

**Comment by ramonamis** [comment]
ok, i also want to mention that the working instance has this structure:

(admin1, admin2, admin3) with no trailing ,

**Comment by gbin** [comment]
So `('toto')` is the sequence of chrs `'t', 'o', 't', 'o'`
And ` (`toto`,)` is the sequence of strings with one element 'toto'

**Comment by ramonamis** [comment]
@gbin exactly. maybe it should be added to documentation, even if it's expected python tuple behaviour. 

About the urllib convert issue above, do you have any input? I had to modify 2 files manually so I could start the bot. :( 

Thanks

**Comment by gbin** [comment]
We could accept both : a string or a sequence as probably a lot of errbot installs have only one admin. 
(split that into a different issue: #461)

**Comment by gbin** [comment]
I am also puzzled by the other error, if I do from a py2 virtualenv:

./errbot/py2conv.py

I end up with that:

```
(errpy2)➜  err (3.0) ✗ cat errbot/core_plugins/vcheck.py
from __future__ import absolute_import
from urllib2 import urlopen
from urllib2 import HTTPError, URLError

from errbot import BotPlugin
from errbot.version import VERSION
from errbot.utils import version2array

HOME = u'http://gbin.github.io/err/version'

installed_version = version2array(VERSION)
```

Is it an installer problem ?

**Comment by gbin** [comment]
Doing:

```
mkvirtualenv -p `which python2` throwaway
pip install err
```

I see `RefactoringTool: errbot/core_plugins/vcheck.py` during the install.

then:

```python
(throwaway)➜  err (3.0) cat ~/.virtualenvs/throwaway/lib/python2.7/site-packages/errbot/core_plugins/vcheck.py
from __future__ import absolute_import
from urllib2 import urlopen
from urllib2 import HTTPError, URLError

from errbot import BotPlugin
from errbot.version import VERSION
from errbot.utils import version2array
```

So I think it is something weird on your side (maybe a conflict with another checked out errbot not converted in py3 or something like that).

Closing the bug.

**Comment by ramonamis** [comment]
@gbin nice, thank you very much :dancers: 
i'll check the urllib problem again, maybe on a different machine
