### ISSUE TITLE
& rendering with XMPP

### ISSUE THREAD

**Issue by gbin** [gbin/err#465]
```You missed the following assigments:
Read chapter 20 in the text book and complete labs 21 & 24. Skip labs 22 and 23 as we will cover those next week.```

output should work according to the MD spec but produces:

```
Traceback (most recent call last):
File "c:\python34\lib\site-packages\errbot\errBot.py", line 360, in _execute_and_send
send_reply(process_reply(reply))
File "c:\python34\lib\site-packages\errbot\errBot.py", line 348, in send_reply
self.send_simple_reply(mess, part, cmd in self.bot_config.DIVERT_TO_PRIVATE)
File "c:\python34\lib\site-packages\errbot\errBot.py", line 116, in send_simple_reply
self.send_message(self.build_reply(mess, text, private))
File "c:\python34\lib\site-packages\errbot\backends\xmpp.py", line 541, in send_message
mhtml=html)
File "c:\python34\lib\site-packages\sleekxmpp\basexmpp.py", line 545, in send_message
mhtml, mfrom, mnick).send()
File "c:\python34\lib\site-packages\sleekxmpp\basexmpp.py", line 500, in make_message
message['html']['body'] = mhtml
File "c:\python34\lib\site-packages\sleekxmpp\xmlstream\stanzabase.py", line 770, in setitem
getattr(self, set_method)(value, **kwargs)
File "c:\python34\lib\site-packages\sleekxmpp\plugins\xep_0071\stanza.py", line 42, in set_body
xhtml = ET.fromstring(content)
File "c:\python34\lib\xml\etree\ElementTree.py", line 1325, in XML
parser.feed(text)
File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 4, column 56
```

**Comment by gbin** [comment]
Apparently this is fixed:

╌╌[MD  ]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
ca & la
21:22:32 DEBUG    errbot.errBot             Trigger callback_message on Backup


╌╌[HTML]╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
<p>ca &amp; la</p>
