### ISSUE TITLE
base.html not found

### ISSUE THREAD

**Issue by Eagllus** [gbin/err#525]
in `err/docs/user_guide/plugin_development/messaging.rst` its said to use 
```
{% extends "base.html" %}
{% block body %}
<p style='font-weight:bold'>Hello, {{name}}!</p>
{% endblock %}
```

doing this gives me the following message
```
Traceback (most recent call last):
  File "/virtualenv/xmpp34/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/virtualenv/xmpp34/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/virtualenv/xmpp34/lib/python3.4/site-packages/errbot/core_plugins/wsview.py", line 74, in __call__
    response = self.func(request, **kwargs)
  File "/home/xmppbot/sudo/data/plugins/err-githubhook/githubhook.py", line 396, in receive
    message = getattr(self, message_function)(body, repo)
  File "/home/xmppbot/sudo/data/plugins/err-githubhook/githubhook.py", line 508, in msg_push
    return tenv().get_template('push.html').render(locals().copy())
  File "/virtualenv/xmpp34/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/virtualenv/xmpp34/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/virtualenv/xmpp34/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/xmppbot/sudo/data/plugins/err-githubhook/templates/push.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/virtualenv/xmpp34/lib/python3.4/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
```

I'm wondering is this related to the plugin `err-githubhook` or something else?

**Comment by zoni** [comment]
This is because of a breaking change in the 3.x release series. We changed the templating format to be based on Markdown now.

Issues #511 and #521 deal with the still-outdated documentation on that part.

Basically the templates in `err-githubhook` will have to be adjusted to Markdown format (:cry:) without any of the `{% extends "base.html" %}` stuff, but then they'll work.

**Comment by Eagllus** [comment]
Thank you, will update the template for the plugin then

**Comment by zoni** [comment]
Hmmmmmm. I believe we actually still run the templates through Jinja for processing prior to rendering the markdown, so that should continue to work as-is (I can verify that later, if you want).

If we don't, I see that as something desirable so I think we should preprocess with Jinja anyway.

**Comment by Eagllus** [comment]
I just converted a template to
```[Github] [{{repo}}] pull request [#{{number}}]({{url}}) {{action}} by {{user}}```
that should make for
```[Github] [eagllus/repo] pull request <a hreft="https://github.com/eagllus/repo">#1</a> opened by Eagllus```

The result is
```[Github] [eagllus/repo] pull request #1 (https://github.com/eagllus/repo/pull/1) opened by Eagllus.```

**Comment by gbin** [comment]
@Eagllus what is your backend ?

**Comment by Eagllus** [comment]
@gbin we use xmpp (if that is what you mean)

**Comment by gbin** [comment]
Ok so it is the intended behavior at the moment: we use plain text on xmpp so errbot cannot materialize the link.

We had to disable xhtml-im (with some formatting and link support) because the client support is really poor.

If you would like to try it anyway, you can uncomment this line: https://github.com/gbin/err/blob/master/errbot/backends/xmpp.py#L534

If you try, please report back your experience with it (with the type of clients you use etc.).

**Comment by zoni** [comment]
Related: #467.
